Apple page
yahir91/Apple-page pull request #1
Opened 2020-05-13 23:46 UTC by yahir91

This project is a clone of an old landing page of apple. This page structure is built using CSS grid and flexbox and I had to use linear-gradient to match the navbar as the original.

2020-05-14 17:10 UTC, rammazzoti2000 commented
## Pull Request under review byAlexandru Bangau (TSE)

2020-05-14 17:50 UTC, rammazzoti2000 requested changes
### Hello @yahir91 :wave: my name is Alexandru, your code reviewer for this project
Your project is really great, you used HTML semantic, no css bad practices (repeating rules) except for one only, great job on the use of css background and gradients :+1: 
The project is almost ready for approval except for some small issues :eyes: 
### Required Changes :construction: :construction_worker: 
- [ ] The page has an horizontal overflow, remove it by removing the width in the main selector
- [ ] Remove text-decoration for the elements in navbar `text-decoration: none;`
- [ ] The width for the footer is better to change it to `fit-content` so that it uses only the space needed based on the available space, see the inline-comment bellow :point_down: 
- [ ] Also you have a repeating rule (`font-weight: 400`) in the footer anyway the value 400 refers to the normal font-weight so you don't need it, remove it; see the inline comments bellow :point_down: 
### Optional :smile: 
- [ ] Would be great to have a live demo link in the readme file
### <em>Kindly fix the REQUIRED issues and send another code review request.

Cheers and Happy coding! :clap: 

##### Code review by Alexandru Bangau

(Feel free to contact me on slack by the handle of alexandru if you have any additional question)</em>

### :stop_sign:  Status: Changes required.

2020-05-14 17:50 UTC, rammazzoti2000 commented on style.css
> +  grid-template-columns: repeat(4 1fr);
missed the comma after 4
`grid-template-columns: repeat(4, 1fr)`

2020-05-14 17:50 UTC, rammazzoti2000 commented on style.css
> +  width: 1440px;
this width is causing heavy horizontal overflow, remove it to fix the issue

2020-05-14 17:50 UTC, rammazzoti2000 commented on style.css
> +nav a {
remove text-decoration for elements in navbar
`text-decoration: none;`

2020-05-14 17:50 UTC, rammazzoti2000 commented on style.css
> +  width: 1000px;
change width to 
```
width: -webkit-fit-content;
width: -moz-fit-content;
width: fit-content;
```

will be cross platform(browser) compatible and will use the space available but never less than the min-content and never more than the max-content"

2020-05-14 17:50 UTC, rammazzoti2000 commented on style.css
> +  font-weight: 400;
this it seems it has no effect since 400 is the same as normal thickness, you can remove it

2020-05-14 17:50 UTC, rammazzoti2000 commented on style.css
> +  font-weight: 400;
this it seems it has no effect since 400 is the same as normal thickness, you can remove it

2020-05-14 17:50 UTC, rammazzoti2000 commented on style.css
> +  font-weight: 400;
this it seems it has no effect since 400 is the same as normal thickness, you can remove it

2020-05-14 17:55 UTC, rammazzoti2000 requested changes
### :stop_sign: Status: Required Changes

2020-05-15 10:17 UTC, trekab approved these changes
# Approved! :tada: 
Congratulations, @team!!! :clap: You may merge to master, submit the project completion form and continue to the next project.

Happy coding! :wink:
__Treasure Kabareebe__
[GitHub](https://github.com/trekab) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

2020-05-15 14:03 UTC, merged